### ISSUE TITLE
$ref issues

### ISSUE THREAD

**Issue by McFoggy** [lbovet/docson#29] opened 2015-07-24 07:23 UTC
Hi,

I am integrating docson with [RAML](http://raml.org/) (both [api-console](http://raml.org/projects.html#tools-api-console) & [api-designer](http://raml.org/projects.html#tools-api-designer)).

I am facing issues while rendering simple json-schemas that are only a reference to an externally defined one (ie their own json files).
I have built a simple demo app that shows my problems : https://github.com/McFoggy/docson-reference-demo.

![image](https://cloud.githubusercontent.com/assets/1119660/8869532/12dc8d30-31e5-11e5-9703-fe3d4897e7a6.png)
## Problems
1. schemas loaded using '$ref' at the root do not load correctly: click on any `ref` link and `Load from schema`
2. when ID is defined on a schema, the context is lost when loading a sub schema: click on latest `refWithId` and `Load from schema`. The referenced `address.json` is in 404 because loaded from a bad URL

I would really appreciate some feedback in order to either establish that either I am doing something totally wrong or that I am facing a bug.

**Comment by McFoggy** [comment] 2015-07-28 07:31
In order to ease tests, I have pushed a running demo application at: http://blog.matthieu.brouillard.fr/docson-reference-demo/app/

Thanks for any help.

**Comment by rom1504** [comment] 2015-09-02 20:15
I'm currently having I think the same issue : [this schema](https://github.com/PrismarineJS/minecraft-data/blob/932b0c3bdb8f84825a55c4d78e28381eb5a6dab3/enums_schemas/protocol_schema.json#L216) doesn't work with docson.

Did you find any way to fix it @McFoggy ?

**Comment by McFoggy** [comment] 2015-09-02 20:42
not at all but I admit that I had to switch to another topic meanwhile. If you find something, please post a comment.

**Comment by rom1504** [comment] 2015-09-02 22:19
alright I fixed it in #35 @McFoggy

**Comment by cneijenhuis** [comment] 2015-09-03 09:16
@McFoggy are you sure only a `$ref` is a valid schema? I'd say no, because a schema needs to contain `$schema` [at the root](http://json-schema.org/latest/json-schema-core.html#anchor23). Also, `$ref` must be the only field in the object, so you can't create something like this:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "..."
}
```

I can think of only one hack to create a schema that exists only of a reference:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "oneOf": [{"$ref": "..."}]
}
```
It basically says: This is a schema. It must contain at least one of the following elements. Since there is only one element, it must contain that one. :neutral_face: 
You could also use `anyOf` or `allOf`, they all have the same semantic when the list only contains one element.

It's an ugly hack, and Docson will render the `oneOf`. I'm facing similar issues when working with `$ref`...

**Comment by cneijenhuis** [comment] 2015-09-03 09:21
@rom1504 What are you trying to achieve with this: `"type": {"$ref": "..."}`?

It is not a valid schema, according to the spec: 
```
The value of this keyword type MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.

String values MUST be one of the seven primitive types defined by the core specification. 
```
http://json-schema.org/latest/json-schema-validation.html#anchor79

Probably the hack I described above should work for your use case as well, but it's not pretty... :disappointed:

**Comment by rom1504** [comment] 2015-09-03 10:27
@cneijenhuis Yeah you're right, the `"type": {"$ref": "..."}` doesn't seem valid (https://www.npmjs.com/package/jsonschema has no problem with it though...)

Why does the `$ref` have to be the only field in the object ? I can't find this in the reference, and http://jsonschemalint.com/draft4/ says it's valid to have 
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "..."
}
```

**Comment by McFoggy** [comment] 2015-09-03 11:04
@cneijenhuis I do not find in the spec the fact that `$schema` is mandatory. Explicitly at the [pointer](http://json-schema.org/latest/json-schema-core.html#rfc.section.6.1) you mention it is written: `It is _RECOMMENDED_ that schema authors include this keyword in their schemas.`.

Also the schema-core itself doesn't defined any `required` attribute.

But you are right that on the other hand I am not even sure that the a schema with only a `$ref` is a valid schema.

**Comment by rom1504** [comment] 2015-09-03 11:24
I believe a schema with only a `$ref` is valid. Docson even has a test for this https://github.com/lbovet/docson/blob/master/tests/ref.json#L113 which is still broken but for different reasons now.

I removed the type thing that was indeed wrong in my PR and added a regression test https://github.com/lbovet/docson/pull/35/files#diff-e039c6140a632eef1d13cd1ceba8bb12R160 that doesn't work with master code, but works with my PR (#35)

**Comment by cneijenhuis** [comment] 2015-09-03 11:25
@rom1504 The References are defined in another draft, there it says:

> Any members other than "$ref" in a JSON Reference object SHALL be ignored.
> - http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3

So, yeah, it's not an invalid Reference-object but `$schema` would be ignored... Therefore it doesn't make a difference whether you add `$schema` or not.

@McFoggy You are right. I understood this sentence wrong: ```This keyword MUST be located at the root of a JSON Schema.``` I understood it as in "You must include the keyword at the root". But it probably means "If you include the keyword, it must be located at the root".

**Comment by cneijenhuis** [comment] 2015-09-03 11:46
@rom1504 Okay, after re-reading I guess a schema with only `$ref` is valid, although it feels strange.

I still think this: https://github.com/lbovet/docson/blob/master/tests/ref.json#L113 is not what it intends to be. According to [the JSON Reference draft](http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3), you need to ignore the other fields (in this case `definitions`).

There is also a good reason for this, because if you don't ignore other fields, you end up with conflicts. Say you have two schemas:
```
(foo.schema.json)
{
  "type" : "object" 
}
```
```
(bar.schema.json)
{
  "type" : "string",
  "$ref" : "foo.schema.json"
}
````
Then you need to ignore `"type" : "string"` in `bar.schema.json` to end up with something valid.

**Comment by rom1504** [comment] 2015-09-03 12:01
Yeah I guess you are right, the spec does say every other members should be ignored.

I guess it makes some kind of sense, I'll change my PR to ignore all other members.

**Comment by artem-korolev** [comment] 2016-03-11 10:56
have no time to get into your thread, but I created one pull request that is trying to solve one of the problem with $ref. check it please - https://github.com/lbovet/docson/pull/47

**Comment by yanick** [comment] 2018-02-20 03:07
I'm fairly sure this issue is now resolved. I'll close it. If I'm wrong and the issue is still not vanquished, please let me know.

**Closed by yanick** 2018-02-20 03:07 UTC
